/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alunos
 */
public class loteriaform extends javax.swing.JFrame {
  loteria l = new loteria();
    public loteriaform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        texto1 = new javax.swing.JLabel();
        Caixa1 = new javax.swing.JTextField();
        Caixa2 = new javax.swing.JTextField();
        Caixa3 = new javax.swing.JTextField();
        Caixa5 = new javax.swing.JTextField();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        sortear = new javax.swing.JButton();
        sortear1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        texto7 = new javax.swing.JLabel();
        texto8 = new javax.swing.JLabel();
        texto9 = new javax.swing.JLabel();
        texto10 = new javax.swing.JLabel();
        Caixa9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numerosacertos = new javax.swing.JTextField();
        premiacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ResultSort1 = new javax.swing.JTextField();
        ResultSort2 = new javax.swing.JTextField();
        ResultSort3 = new javax.swing.JTextField();
        ResultSort4 = new javax.swing.JTextField();
        ResultSort5 = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto1.setText("Num1");

        Caixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa1ActionPerformed(evt);
            }
        });

        Caixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa2ActionPerformed(evt);
            }
        });

        Caixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa3ActionPerformed(evt);
            }
        });

        Caixa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa5ActionPerformed(evt);
            }
        });

        texto2.setText("Num2");

        texto3.setText("Num3");

        texto4.setText("Num4");

        texto5.setText("Num5");

        sortear.setText("Sortear");
        sortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortearActionPerformed(evt);
            }
        });

        sortear1.setText("Cadastrar Aposta");
        sortear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortear1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Apostas");

        texto6.setText("Num1");

        texto7.setText("Num2");

        texto8.setText("Num3");

        texto9.setText("Num4");

        texto10.setText("Num5");

        Caixa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caixa9ActionPerformed(evt);
            }
        });

        jLabel2.setText("N° de Acertos");

        jLabel3.setText("Premiação");

        numerosacertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerosacertosActionPerformed(evt);
            }
        });

        premiacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiacaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Sorteados");

        jLabel5.setText("LOTERIA");

        ResultSort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultSort1ActionPerformed(evt);
            }
        });

        ResultSort2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultSort2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(texto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Caixa2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(texto2)
                                .addGap(18, 18, 18)
                                .addComponent(Caixa1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(texto3)
                                .addGap(18, 18, 18)
                                .addComponent(Caixa3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(texto4)
                                .addGap(18, 18, 18)
                                .addComponent(Caixa9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(texto5)
                                .addGap(18, 18, 18)
                                .addComponent(Caixa5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel4)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(texto10)
                                    .addComponent(texto9)
                                    .addComponent(texto8)
                                    .addComponent(texto7)
                                    .addComponent(texto6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResultSort1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResultSort2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResultSort3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResultSort4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ResultSort5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sortear1)
                            .addComponent(sortear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addComponent(premiacao)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(numerosacertos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto1)
                    .addComponent(Caixa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto6)
                    .addComponent(ResultSort1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto2)
                    .addComponent(texto7)
                    .addComponent(ResultSort2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caixa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto3)
                    .addComponent(texto8)
                    .addComponent(ResultSort3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto4)
                    .addComponent(texto9)
                    .addComponent(Caixa9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultSort4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caixa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto5)
                    .addComponent(texto10)
                    .addComponent(ResultSort5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortear1)
                    .addComponent(jLabel2)
                    .addComponent(numerosacertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(premiacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Caixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa1ActionPerformed
       try{ 
            Caixa1.setText(Caixa1.getText());
        }catch(Exception e){
            Caixa1.setText("Erro");
        }
    }//GEN-LAST:event_Caixa1ActionPerformed

    private void Caixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa2ActionPerformed
           try{ 
            Caixa2.setText(Caixa2.getText());
        }catch(Exception e){
            Caixa2.setText("Erro");
        }
    }//GEN-LAST:event_Caixa2ActionPerformed

    private void Caixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa3ActionPerformed
          try{ 
            Caixa3.setText(Caixa3.getText());
        }catch(Exception e){
            Caixa3.setText("Erro");
        }
    }//GEN-LAST:event_Caixa3ActionPerformed

    private void Caixa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa5ActionPerformed
          try{ 
            Caixa5.setText(Caixa5.getText());
        }catch(Exception e){
            Caixa5.setText("Erro");
        }
    }//GEN-LAST:event_Caixa5ActionPerformed

    private void Caixa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caixa9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Caixa9ActionPerformed

    private void premiacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_premiacaoActionPerformed

    private void sortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortearActionPerformed
        l.Sortear();
        ResultSort1.setText((""+l.numsort1));
        ResultSort2.setText((""+l.numsort2));
        ResultSort3.setText((""+l.numsort3));
        ResultSort4.setText((""+l.numsort4));
        ResultSort5.setText((""+l.numsort5));
        l.CalcularAcertos();
        numerosacertos.setText(("" + l.cont));
        l.VerificarPremio(l.cont);
        premiacao.setText((""+l.premio));
        
    }//GEN-LAST:event_sortearActionPerformed

    private void ResultSort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultSort1ActionPerformed
         
    }//GEN-LAST:event_ResultSort1ActionPerformed

    private void ResultSort2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultSort2ActionPerformed
          
    }//GEN-LAST:event_ResultSort2ActionPerformed

    private void sortear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortear1ActionPerformed
                 
    }//GEN-LAST:event_sortear1ActionPerformed

    private void numerosacertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosacertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerosacertosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loteriaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loteriaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loteriaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loteriaform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loteriaform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Caixa1;
    private javax.swing.JTextField Caixa2;
    private javax.swing.JTextField Caixa3;
    private javax.swing.JTextField Caixa5;
    private javax.swing.JTextField Caixa9;
    private javax.swing.JTextField ResultSort1;
    private javax.swing.JTextField ResultSort2;
    private javax.swing.JTextField ResultSort3;
    private javax.swing.JTextField ResultSort4;
    private javax.swing.JTextField ResultSort5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField numerosacertos;
    private javax.swing.JTextField premiacao;
    private javax.swing.JButton sortear;
    private javax.swing.JButton sortear1;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto10;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel texto7;
    private javax.swing.JLabel texto8;
    private javax.swing.JLabel texto9;
    // End of variables declaration//GEN-END:variables
}
